global:
  scrape_interval: 1s  # How often to scrape targets by default.

scrape_configs:
  - job_name: "proxy"
    static_configs:
      - targets: ["proxy:8080"]  # Scrape the proxy's metrics endpoint
